
# =====================================================================
# Excel Comparison Service configuration
# =====================================================================
# Directories scanned for Excel files.

app.files.excelcompare.source-directory=./data/source
app.files.excelcompare.target-directory=./data/target

## sheets level configuration
app.files.recon.customer.Sheet1.unique-row-key=uniqueId,Name
app.files.recon.customer.Sheet1.ignore-columns=CreatedDate,UpdatedDate,name
app.files.recon.customer.Sheet1.header-row-index=2

app.files.recon.order.Sheet1.unique-row-key=uniqueId,Name
app.files.recon.order.Sheet1.ignore-columns=CreatedDate,UpdatedDate,name
app.files.recon.order.Sheet1.header-row-index=2
