spring.application.name=easyexcel-compare
spring.config.import=optional:classpath:/config/excelcompare.properties

logging.file.name=./log/excelcompare.log
# how to disbale banner flag
spring.main.banner-mode=off